"""EMITTER for results/r19_split_half_reliability.json.

Checked in because an independent reviewer found that this file and its sibling -- the two
numbers that close R19's headline escape hatch -- were consumed by headline.py and generated by
NOTHING IN THE REPOSITORY. They were made by a scratchpad script. A result whose generator does
not exist is indistinguishable from a result that was never true, which is this repository's
opening sentence, and it was true of its own two most load-bearing files.

    python3 R19_crossed_position_support/tools/split_half_reliability.py
"""
import json, math, os, random
os.chdir('/home/ivan/AblationNoise')
D = json.load(open('R19_crossed_position_support/results/r19_crossed_qwen2.5-1.5b.json'))
C = D['cells']
NB = D['n_base']
BAND = [(L, h) for L in range(14, D['n_layers']) for h in range(D['n_heads_per_layer'])]
MI = 0                                   # signed_margin_drop, the metric every verdict here uses


def corr(x, y):
    n = len(x); mx, my = sum(x) / n, sum(y) / n
    sx = math.sqrt(sum((a - mx) ** 2 for a in x)); sy = math.sqrt(sum((b - my) ** 2 for b in y))
    return sum((x[i] - mx) * (y[i] - my) for i in range(n)) / (sx * sy) if sx and sy else 0.0


def halves(scope, ia, ib):
    a, b = [], []
    for k in BAND:
        cell = C['L%02dH%02d.%s' % (k[0], k[1], scope)]['base']
        a.append(sum(cell[i][MI] for i in ia) / len(ia))
        b.append(sum(cell[i][MI] for i in ib) / len(ib))
    return a, b


REG_A, REG_B = list(range(0, 32)), list(range(32, 64))
out = {'n_band': len(BAND), 'n_base': NB, 'metric': D['metrics'][MI], 'splits': {}}
for scope in ('final', 'all'):
    a, b = halves(scope, REG_A, REG_B)
    r = corr(a, b)
    sb = 2 * r / (1 + r) if r > -1 else float('nan')       # Spearman-Brown to full length
    # POSITIVE CONTROL: bases are exchangeable by design, so 200 RANDOM half-splits must agree with
    # the registered contiguous one. A contiguous split could otherwise ride the b%8 query/room
    # cycle -- 0..31 and 32..63 each contain every (query, room) pair exactly four times, but the
    # check is cheap and the assumption is not free.
    rng = random.Random(20260728)
    idx = list(range(NB))
    rs = []
    for _ in range(200):
        rng.shuffle(idx)
        ra, rb = halves(scope, idx[:32], idx[32:])
        rs.append(corr(ra, rb))
    rs.sort()
    out['splits'][scope] = {'r_halfsplit': r, 'r_full_spearman_brown': sb,
                            'random_split_median': rs[100], 'random_split_lo': rs[5],
                            'random_split_hi': rs[194], 'n_random_splits': len(rs)}

rf = out['splits']['final']['r_full_spearman_brown']
ra = out['splits']['all']['r_full_spearman_brown']
out['registered_windows'] = {
    'pooled_world_S_needs_r_yy_in': [0.5986, 0.7390],
    'within_layer_world_S_needs_r_yy_in': [0.7067, 0.8725],
    'measured_r_yy_all': ra,
    'inside_pooled_window': 0.5986 <= ra <= 0.7390,
    'inside_within_layer_window': 0.7067 <= ra <= 0.8725,
    'registered_prediction': 'r_yy(all) > 0.7390, confidence 0.75',
    'prediction_correct': ra > 0.7390}
json.dump(out, open('R19_crossed_position_support/results/r19_split_half_reliability.json', 'w'), indent=1)
for scope in ('final', 'all'):
    s = out['splits'][scope]
    print('%-6s  half-split r %.4f   Spearman-Brown full-length %.4f   | random-split median %.4f [%.4f, %.4f]'
          % (scope, s['r_halfsplit'], s['r_full_spearman_brown'], s['random_split_median'],
             s['random_split_lo'], s['random_split_hi']))
w = out['registered_windows']
print()
print('World S (pooled)       needs r_yy(all) in [%.4f, %.4f]  ->  measured %.4f  INSIDE: %s'
      % (w['pooled_world_S_needs_r_yy_in'][0], w['pooled_world_S_needs_r_yy_in'][1], ra, w['inside_pooled_window']))
print("World S (within-layer) needs r_yy(all) in [%.4f, %.4f]  ->  measured %.4f  INSIDE: %s"
      % (w['within_layer_world_S_needs_r_yy_in'][0], w['within_layer_world_S_needs_r_yy_in'][1], ra, w['inside_within_layer_window']))
print('registered prediction r_yy(all) > 0.7390 at confidence 0.75  ->  %s' % w['prediction_correct'])
